package com.labmanagement.researchlabmanagement;

public enum MenuOption {
    ADD_EQUIPMENT, UPDATE_EQUIPMENT, REMOVE_EQUIPMENT, VIEW_EQUIPMENT, VIEW_SINGLE_EQUIPMENT,
    ADD_LABORATORY, UPDATE_LABORATORY, REMOVE_LABORATORY, VIEW_LABORATORY, VIEW_SINGLE_LABORATORY,
    ADD_RESEARCH, UPDATE_RESEARCH, REMOVE_RESEARCH, VIEW_RESEARCH, VIEW_SINGLE_RESEARCH,
    ADD_SCIENTIST, UPDATE_SCIENTIST, REMOVE_SCIENTIST, VIEW_SCIENTIST, VIEW_SINGLE_SCIENTIST,
    VIEW_INVENTORY, VIEW_SINGLE_INVENTORY, EXIT
}